# -*- coding: utf-8 -*-
"""arithmeticoperationusingnumpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oyru6K3VewvBaOVeucfTLK1TWoztk1U6
"""

import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a

b = np.array([7,8,9])
b

np.add(a,b)

np.subtract(b,a)

np.multiply(a,b)

np.divide(a,b)

np.power(a,2)

np.power(b,3)

np.power(a,b)
x= np.array([i for i in range (10)])
x
np.where(x%2==0 ,'Even','Odd')
cond_list= [x<5,x>5]
choice_list = [x**2,x**5]
np.select(cond_list,choice_list,default=x)
