# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_Fl3Wj28GCuoATux7xNCbFYIqoUR4wH
"""

import pandas as pd
l = [x for x in range(5)]
s = pd.Series(l)
s

s =pd.Series(l,index=['p','y','t','h','0'])
s

s['p']

s =pd.Series(l,index=['p','p','t','h','0'])
s['p']

dict = {'p':1,'y':2,'t':3,'h':4,'o':5,'n':6}
s= pd.Series(dict)
s

s= pd.Series(dict,index=['p','y','t'])
s

s= pd.Series(dict,index=['p','y','t','a'])
s

import pandas as pd
l = [x for x in range(10)]
s = pd.Series(l)
s

s.iloc[0]

s.iloc[9]

s.iat[5]

s[0]

s[0:5]

s[5:9]

s[0:-1]

s.where(s%2==0)

s.where(s%2==0,s**2)

s.where(s%2==0,inplace=True)
s

s.dropna()

s.fillna('Filled value')

s.where(s%2==0,'Odd Number')

import pandas as pd
df = pd.DataFrame()
type(df)

df =pd.read_csv('/content/rainfall.csv')
df

df.head(2)

df.tail(3)

df.values

df.iloc[2]

df = pd.read_csv('/content/rainfall.csv',chunksize=2)
for chunksize in df:
  print(chunksize)

df.iloc[11]