# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJzS-NK1EMpgGV3LXHx4S49aw47-SOrd
"""

import pandas as pd
df = pd.read_csv('/content/Book1.csv')
df

df.set_index(['slno','Place'],inplace=True)
df.index

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data.csv')

df.plot(kind = 'scatter', x = 'Duration', y = 'Calories')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data.csv')

df.plot()

plt.show()

df["Duration"].plot(kind = 'hist')